namespace RoadOps.Application.Repositories;

/// <summary>Stores photo files. Keys are always generated by the server, never taken from a client.</summary>
public interface IPhotoStorage
{
    Task SaveAsync(string key, Stream content, CancellationToken cancellationToken = default);

    /// <summary>Opens a stored file for reading, or returns null if it does not exist.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default);

    Task DeleteAsync(string key, CancellationToken cancellationToken = default);
}
