// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoadOps.Infrastructure.Data;

#nullable disable

namespace RoadOps.Infrastructure.Migrations
{
    [DbContext(typeof(RoadOpsDbContext))]
    [Migration("20260926095015_AddPhotosAndSoftVoid")]
    partial class AddPhotosAndSoftVoid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoadOps.Domain.Entities.PavedRoadRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<double>("ChainageFrom")
                        .HasColumnType("double precision")
                        .HasColumnName("chainage_from");

                    b.Property<double>("ChainageTo")
                        .HasColumnType("double precision")
                        .HasColumnName("chainage_to");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<int>("Degree")
                        .HasColumnType("integer")
                        .HasColumnName("degree");

                    b.Property<double?>("DepthMm")
                        .HasColumnType("double precision")
                        .HasColumnName("depth_mm");

                    b.Property<string>("DistressType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("distress_type");

                    b.Property<int>("Extent")
                        .HasColumnType("integer")
                        .HasColumnName("extent");

                    b.PrimitiveCollection<string[]>("ImagePaths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_paths");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("LengthM")
                        .HasColumnType("double precision")
                        .HasColumnName("length_m");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recommended_action");

                    b.Property<string>("RidingQuality")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("riding_quality");

                    b.Property<double>("RutDepthMm")
                        .HasColumnType("double precision")
                        .HasColumnName("rut_depth_mm");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("section_id");

                    b.Property<string>("SkidResistance")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("skid_resistance");

                    b.Property<string>("StdRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("std_ref");

                    b.Property<int>("SurfaceType")
                        .HasColumnType("integer")
                        .HasColumnName("surface_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<string>("VoidedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("voided_by");

                    b.Property<double?>("WidthM")
                        .HasColumnType("double precision")
                        .HasColumnName("width_m");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_paved_road_records");

                    b.HasIndex("ChainageFrom")
                        .HasDatabaseName("ix_paved_road_records_chainage_from");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_paved_road_records_created_at");

                    b.HasIndex("DistressType")
                        .HasDatabaseName("ix_paved_road_records_distress_type");

                    b.HasIndex("CreatedBy", "CreatedAt")
                        .HasDatabaseName("ix_paved_road_records_created_by_created_at");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_paved_road_records_latitude_longitude");

                    b.HasIndex("SectionId", "ChainageFrom")
                        .HasDatabaseName("ix_paved_road_records_section_id_chainage_from");

                    b.HasIndex("WorkspaceId", "ChainageFrom")
                        .HasDatabaseName("ix_paved_road_records_workspace_id_chainage_from");

                    b.ToTable("paved_road_records", (string)null);
                });

            modelBuilder.Entity("RoadOps.Domain.Entities.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AttachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("RecordId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("record_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_photos_record_id");

                    b.HasIndex("UploadedBy", "UploadedAt")
                        .HasDatabaseName("ix_photos_uploaded_by_uploaded_at");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("RoadOps.Domain.Entities.RoadSection", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<double>("ChainageFrom")
                        .HasColumnType("double precision")
                        .HasColumnName("chainage_from");

                    b.Property<double>("ChainageTo")
                        .HasColumnType("double precision")
                        .HasColumnName("chainage_to");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("section_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_road_sections");

                    b.HasIndex("SectionName")
                        .HasDatabaseName("ix_road_sections_section_name");

                    b.HasIndex("WorkspaceId", "ChainageFrom")
                        .HasDatabaseName("ix_road_sections_workspace_id_chainage_from");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_road_sections_workspace_id_created_at");

                    b.ToTable("road_sections", (string)null);
                });

            modelBuilder.Entity("RoadOps.Domain.Entities.Workspace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assessment_type");

                    b.Property<string>("Corridor")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("corridor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SurveyYear")
                        .HasColumnType("integer")
                        .HasColumnName("survey_year");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_workspaces_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_workspaces_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workspaces_status");

                    b.HasIndex("Corridor", "SurveyYear")
                        .HasDatabaseName("ix_workspaces_corridor_survey_year");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("RoadOps.Domain.Entities.PavedRoadRecord", b =>
                {
                    b.HasOne("RoadOps.Domain.Entities.RoadSection", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paved_road_records_road_sections_section_id");

                    b.HasOne("RoadOps.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paved_road_records_workspaces_workspace_id");
                });

            modelBuilder.Entity("RoadOps.Domain.Entities.Photo", b =>
                {
                    b.HasOne("RoadOps.Domain.Entities.PavedRoadRecord", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_photos_paved_road_records_record_id");
                });

            modelBuilder.Entity("RoadOps.Domain.Entities.RoadSection", b =>
                {
                    b.HasOne("RoadOps.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_road_sections_workspaces_workspace_id");
                });
#pragma warning restore 612, 618
        }
    }
}
